# config/packages/messenger.yaml
framework:
    messenger:
        failure_transport: failed

        transports:
            # Use Doctrine ORM for both async and failed transports
            async: 'doctrine://default?queue_name=chat_messages'  # Store chat messages in the database
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async  # Keep this for notifier integration if needed
            Symfony\Component\Notifier\Message\SmsMessage: async
            'App\Message\ChatMessage': async  # Route your custom ChatMessage to the async transport