security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      user_checker: App\Security\UserChecker
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\AppAuthenticator #hethy mta3 approuvé et désaprouvé
      form_login:
        login_path: app_login
        check_path: app_login
        failure_path: app_not_approved
        enable_csrf: true
        username_parameter: email
        password_parameter: motDePasse
      logout:
        path: app_logout
        target: app_login
      entry_point: form_login # Set the entry point to "form_login"

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }

    - { path: ^/patient, roles: ROLE_PATIENT }
    - { path: ^/soignant, roles: ROLE_SOIGNANT }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/connect/google, roles: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
    
    